//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyiv {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Ресурси {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ресурси() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kyiv.Ресурси", typeof(Ресурси).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your locale:.
        /// </summary>
        internal static string ВиберітьКультуру {
            get {
                return ResourceManager.GetString("ВиберітьКультуру", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable implicit addressing.
        /// </summary>
        internal static string ВключаєНеявнуАдресацію {
            get {
                return ResourceManager.GetString("ВключаєНеявнуАдресацію", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random number generator.
        /// </summary>
        internal static string ГенераторВипадковихЧисел {
            get {
                return ResourceManager.GetString("ГенераторВипадковихЧисел", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        internal static string Команда {
            get {
                return ResourceManager.GetString("Команда", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty command.
        /// </summary>
        internal static string Команда00 {
            get {
                return ResourceManager.GetString("Команда00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition.
        /// </summary>
        internal static string Команда01 {
            get {
                return ResourceManager.GetString("Команда01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substraction.
        /// </summary>
        internal static string Команда02 {
            get {
                return ResourceManager.GetString("Команда02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands addition.
        /// </summary>
        internal static string Команда03 {
            get {
                return ResourceManager.GetString("Команда03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed comparison.
        /// </summary>
        internal static string Команда04 {
            get {
                return ResourceManager.GetString("Команда04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsigned comparison.
        /// </summary>
        internal static string Команда05 {
            get {
                return ResourceManager.GetString("Команда05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulo substraction.
        /// </summary>
        internal static string Команда06 {
            get {
                return ResourceManager.GetString("Команда06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclic addition.
        /// </summary>
        internal static string Команда07 {
            get {
                return ResourceManager.GetString("Команда07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication without rounding.
        /// </summary>
        internal static string Команда10 {
            get {
                return ResourceManager.GetString("Команда10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication with rounding.
        /// </summary>
        internal static string Команда11 {
            get {
                return ResourceManager.GetString("Команда11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        internal static string Команда12 {
            get {
                return ResourceManager.GetString("Команда12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical shift.
        /// </summary>
        internal static string Команда13 {
            get {
                return ResourceManager.GetString("Команда13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical addition.
        /// </summary>
        internal static string Команда14 {
            get {
                return ResourceManager.GetString("Команда14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical multiplication.
        /// </summary>
        internal static string Команда15 {
            get {
                return ResourceManager.GetString("Команда15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precision comparison.
        /// </summary>
        internal static string Команда16 {
            get {
                return ResourceManager.GetString("Команда16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equivalence.
        /// </summary>
        internal static string Команда17 {
            get {
                return ResourceManager.GetString("Команда17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entering numbers.
        /// </summary>
        internal static string Команда20 {
            get {
                return ResourceManager.GetString("Команда20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entering commands.
        /// </summary>
        internal static string Команда21 {
            get {
                return ResourceManager.GetString("Команда21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output codes.
        /// </summary>
        internal static string Команда22 {
            get {
                return ResourceManager.GetString("Команда22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing to reel.
        /// </summary>
        internal static string Команда23 {
            get {
                return ResourceManager.GetString("Команда23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading from reel.
        /// </summary>
        internal static string Команда24 {
            get {
                return ResourceManager.GetString("Команда24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to reel.
        /// </summary>
        internal static string Команда25 {
            get {
                return ResourceManager.GetString("Команда25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting group operation.
        /// </summary>
        internal static string Команда26 {
            get {
                return ResourceManager.GetString("Команда26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish group operation.
        /// </summary>
        internal static string Команда27 {
            get {
                return ResourceManager.GetString("Команда27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditional jump to subroutine.
        /// </summary>
        internal static string Команда30 {
            get {
                return ResourceManager.GetString("Команда30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditional jump based on sign.
        /// </summary>
        internal static string Команда31 {
            get {
                return ResourceManager.GetString("Команда31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump based on return register.
        /// </summary>
        internal static string Команда32 {
            get {
                return ResourceManager.GetString("Команда32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Команда33 {
            get {
                return ResourceManager.GetString("Команда33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump based on fixator.
        /// </summary>
        internal static string Команда34 {
            get {
                return ResourceManager.GetString("Команда34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalization.
        /// </summary>
        internal static string Команда35 {
            get {
                return ResourceManager.GetString("Команда35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        internal static string Крок {
            get {
                return ResourceManager.GetString("Крок", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency stop.
        /// </summary>
        internal static string МіткаАварійнаЗупинка {
            get {
                return ResourceManager.GetString("МіткаАварійнаЗупинка", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block of emergency stop.
        /// </summary>
        internal static string МіткаБлокировкаАварийноїЗупинки {
            get {
                return ResourceManager.GetString("МіткаБлокировкаАварийноїЗупинки", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer output.
        /// </summary>
        internal static string МіткаВивідПрінтера {
            get {
                return ResourceManager.GetString("МіткаВивідПрінтера", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well-known adresses.
        /// </summary>
        internal static string МіткаВідоміАдреси {
            get {
                return ResourceManager.GetString("МіткаВідоміАдреси", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading wired subroutine.
        /// </summary>
        internal static string МіткаПідгрузкаЗашитихПідпрограм {
            get {
                return ResourceManager.GetString("МіткаПідгрузкаЗашитихПідпрограм", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable emergency stop during overflow in arithmetic operations.
        /// </summary>
        internal static string ПідказкаАварійнаЗупинка {
            get {
                return ResourceManager.GetString("ПідказкаАварійнаЗупинка", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block emergency stop during overflow in arithmetic operations.
        /// </summary>
        internal static string ПідказкаБлокировкаАварийноїЗупинки {
            get {
                return ResourceManager.GetString("ПідказкаБлокировкаАварийноїЗупинки", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the button to change the current command to start a subroutine written in the ROM. You can press the Step button for step-by-step debugging..
        /// </summary>
        internal static string ПідказкаПідгрузкаЗашитихПідпрограм {
            get {
                return ResourceManager.GetString("ПідказкаПідгрузкаЗашитихПідпрограм", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About project.
        /// </summary>
        internal static string ПроПроект {
            get {
                return ResourceManager.GetString("ПроПроект", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registers.
        /// </summary>
        internal static string Регистри {
            get {
                return ResourceManager.GetString("Регистри", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle finish register.
        /// </summary>
        internal static string РегістрЗакінченняЦиклу {
            get {
                return ResourceManager.GetString("РегістрЗакінченняЦиклу", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command counter register.
        /// </summary>
        internal static string РегістрЛікувальникаКоманд {
            get {
                return ResourceManager.GetString("РегістрЛікувальникаКоманд", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle counter register.
        /// </summary>
        internal static string РегістрЛікувальнихЦиклу {
            get {
                return ResourceManager.GetString("РегістрЛікувальнихЦиклу", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return register.
        /// </summary>
        internal static string РегістрПовернення {
            get {
                return ResourceManager.GetString("РегістрПовернення", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current command register.
        /// </summary>
        internal static string РегістрПоточноїКоманди {
            get {
                return ResourceManager.GetString("РегістрПоточноїКоманди", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string СторінкаГоловна {
            get {
                return ResourceManager.GetString("СторінкаГоловна", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompiler.
        /// </summary>
        internal static string СторінкаДекомпілятор {
            get {
                return ResourceManager.GetString("СторінкаДекомпілятор", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disassembler.
        /// </summary>
        internal static string СторінкаДізасемблер {
            get {
                return ResourceManager.GetString("СторінкаДізасемблер", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        internal static string СторінкаКоманди {
            get {
                return ResourceManager.GetString("СторінкаКоманди", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constants.
        /// </summary>
        internal static string СторінкаКонстанти {
            get {
                return ResourceManager.GetString("СторінкаКонстанти", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inaccuracies.
        /// </summary>
        internal static string СторінкаНеточності {
            get {
                return ResourceManager.GetString("СторінкаНеточності", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM.
        /// </summary>
        internal static string СторінкаОЗП {
            get {
                return ResourceManager.GetString("СторінкаОЗП", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROM.
        /// </summary>
        internal static string СторінкаПЗП {
            get {
                return ResourceManager.GetString("СторінкаПЗП", resourceCulture);
            }
        }
    }
}
