// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Kyiv.Tests
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class КонстантиУМашиніFeature : object, global::Xunit.IClassFixture<КонстантиУМашиніFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("uk"), "", "Константи у машині", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Константи.feature"
#line hidden
        
        public КонстантиУМашиніFeature(КонстантиУМашиніFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Константи.feature.ndjson", 58);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Постоянно-спаянные константы")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Константи у машині")]
        [global::Xunit.TraitAttribute("Description", "Постоянно-спаянные константы")]
        [global::Xunit.InlineDataAttribute("3010", "\'00 0001 0000 0000\'", "0", new string[0])]
        [global::Xunit.InlineDataAttribute("3011", "\'00 0000 0001 0000\'", "1", new string[0])]
        [global::Xunit.InlineDataAttribute("3012", "\'00 0000 0000 0001\'", "2", new string[0])]
        [global::Xunit.InlineDataAttribute("3013", "\'00 0001 0001 0001\'", "3", new string[0])]
        [global::Xunit.InlineDataAttribute("3014", "\'00 0001 0001 0000\'", "4", new string[0])]
        [global::Xunit.InlineDataAttribute("3015", "\'00 0000 0001 0001\'", "5", new string[0])]
        [global::Xunit.InlineDataAttribute("3016", "\'00 0001 0000 0001\'", "6", new string[0])]
        [global::Xunit.InlineDataAttribute("3017", "\'00 0002 0000 0000\'", "7", new string[0])]
        [global::Xunit.InlineDataAttribute("3020", "\'00 0000 0002 0000\'", "8", new string[0])]
        [global::Xunit.InlineDataAttribute("3021", "\'00 0000 0000 0002\'", "9", new string[0])]
        [global::Xunit.InlineDataAttribute("3022", "\'00 7777 0000 0000\'", "10", new string[0])]
        [global::Xunit.InlineDataAttribute("3023", "\'00 0000 7777 0000\'", "11", new string[0])]
        [global::Xunit.InlineDataAttribute("3024", "\'00 0000 0000 7777\'", "12", new string[0])]
        [global::Xunit.InlineDataAttribute("3025", "\'37 0000 0000 0000\'", "13", new string[0])]
        [global::Xunit.InlineDataAttribute("3026", "\'20 0000 0000 0000\'", "14", new string[0])]
        [global::Xunit.InlineDataAttribute("3027", "\'37 0000 7777 7777\'", "15", new string[0])]
        [global::Xunit.InlineDataAttribute("3030", "\'00 7777 7777 7777\'", "16", new string[0])]
        [global::Xunit.InlineDataAttribute("3031", "\'37 7777 0000 7777\'", "17", new string[0])]
        [global::Xunit.InlineDataAttribute("3032", "\'37 7777 7777 0000\'", "18", new string[0])]
        [global::Xunit.InlineDataAttribute("3033", "\'00 7777 0000 7777\'", "19", new string[0])]
        [global::Xunit.InlineDataAttribute("3034", "\'00 0000 7777 7777\'", "20", new string[0])]
        [global::Xunit.InlineDataAttribute("3035", "\'17 7777 7777 7777\'", "21", new string[0])]
        [global::Xunit.InlineDataAttribute("3036", "\'37 7777 7777 7777\'", "22", new string[0])]
        [global::Xunit.InlineDataAttribute("3037", "\'04 6420 2324 1220\'", "23", new string[0])]
        [global::Xunit.InlineDataAttribute("3040", "\'00 0020 0000 0000\'", "24", new string[0])]
        [global::Xunit.InlineDataAttribute("3041", "\'00 0000 0020 0000\'", "25", new string[0])]
        [global::Xunit.InlineDataAttribute("3042", "\'10 0000 0000 0000\'", "26", new string[0])]
        [global::Xunit.InlineDataAttribute("3043", "\'04 0000 0000 0000\'", "27", new string[0])]
        [global::Xunit.InlineDataAttribute("3044", "\'02 0000 0000 0000\'", "28", new string[0])]
        [global::Xunit.InlineDataAttribute("3045", "\'01 0000 0000 0000\'", "29", new string[0])]
        [global::Xunit.InlineDataAttribute("3046", "\'00 2000 0000 0000\'", "30", new string[0])]
        [global::Xunit.InlineDataAttribute("3047", "\'00 0000 0000 0020\'", "31", new string[0])]
        [global::Xunit.InlineDataAttribute("3050", "\'12 0000 0000 0000\'", "32", new string[0])]
        [global::Xunit.InlineDataAttribute("3051", "\'13 0562 0577 3722\'", "33", new string[0])]
        [global::Xunit.InlineDataAttribute("3052", "\'01 4631 4631 4632\'", "34", new string[0])]
        [global::Xunit.InlineDataAttribute("3053", "\'00 1217 2702 4366\'", "35", new string[0])]
        [global::Xunit.InlineDataAttribute("3054", "\'00 0101 4223 3514\'", "36", new string[0])]
        [global::Xunit.InlineDataAttribute("3055", "\'03 1463 1463 1463\'", "37", new string[0])]
        [global::Xunit.InlineDataAttribute("3056", "\'04 6314 6314 6315\'", "38", new string[0])]
        [global::Xunit.InlineDataAttribute("3057", "\'14 6314 6314 6315\'", "39", new string[0])]
        [global::Xunit.InlineDataAttribute("3060", "\'00 0203 0446 7230\'", "40", new string[0])]
        [global::Xunit.InlineDataAttribute("3061", "\'02 4365 6050 7534\'", "41", new string[0])]
        [global::Xunit.InlineDataAttribute("3062", "\'05 0753 4121 7270\'", "42", new string[0])]
        [global::Xunit.InlineDataAttribute("3063", "\'05 0574 6033 3447\'", "43", new string[0])]
        [global::Xunit.InlineDataAttribute("3064", "\'11 0156 5650 1025\'", "44", new string[0])]
        [global::Xunit.InlineDataAttribute("3065", "\'05 7055 2615 4264\'", "45", new string[0])]
        [global::Xunit.InlineDataAttribute("3066", "\'14 4417 6652 1042\'", "46", new string[0])]
        [global::Xunit.InlineDataAttribute("3067", "\'12 1371 4066 7116\'", "47", new string[0])]
        [global::Xunit.InlineDataAttribute("3070", "\'13 2404 7463 1772\'", "48", new string[0])]
        [global::Xunit.InlineDataAttribute("3071", "\'11 1715 1642 6202\'", "49", new string[0])]
        [global::Xunit.InlineDataAttribute("3072", "\'16 3765 6134 5604\'", "50", new string[0])]
        [global::Xunit.InlineDataAttribute("3073", "\'06 3041 0514 7521\'", "51", new string[0])]
        [global::Xunit.InlineDataAttribute("3074", "\'12 6770 2505 4243\'", "52", new string[0])]
        [global::Xunit.InlineDataAttribute("3075", "\'05 2525 2525 2525\'", "53", new string[0])]
        [global::Xunit.InlineDataAttribute("3076", "\'01 4760 1366 1043\'", "54", new string[0])]
        [global::Xunit.InlineDataAttribute("3077", "\'06 7455 7305 2237\'", "55", new string[0])]
        public async global::System.Threading.Tasks.Task Постоянно_СпаянныеКонстанты(string ячейка, string код, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("ячейка", ячейка);
            argumentsOfScenario.Add("код", код);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Постоянно-спаянные константы", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 3
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
 await testRunner.ThenAsync(string.Format("ячейка {0} містить команду {1}", ячейка, код), ((string)(null)), ((global::Reqnroll.Table)(null)), "Тоді ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await КонстантиУМашиніFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await КонстантиУМашиніFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
