// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Kyiv.Tests
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ЛогічніОпераціїFeature : object, global::Xunit.IClassFixture<ЛогічніОпераціїFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("uk"), "", "Логічні операції", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ЛогічніОперації.feature"
#line hidden
        
        public ЛогічніОпераціїFeature(ЛогічніОпераціїFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("ЛогічніОперації.feature.ndjson", 13);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Логічне додавання")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Логічні операції")]
        [global::Xunit.TraitAttribute("Description", "Логічне додавання")]
        [global::Xunit.InlineDataAttribute("\'00 0000 0000 0000\'", "\'37 7777 7777 7777\'", "\'37 7777 7777 7777\'", "0", new string[0])]
        [global::Xunit.InlineDataAttribute("\'25 2525 2525 2525\'", "\'00 0000 0000 0000\'", "\'25 2525 2525 2525\'", "1", new string[0])]
        [global::Xunit.InlineDataAttribute("\'37 7777 7777 7777\'", "\'37 7777 7777 7777\'", "\'37 7777 7777 7777\'", "2", new string[0])]
        public async global::System.Threading.Tasks.Task ЛогічнеДодавання(string парам1, string парам2, string результат, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("парам1", парам1);
            argumentsOfScenario.Add("парам2", парам2);
            argumentsOfScenario.Add("результат", результат);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Логічне додавання", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 3
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await testRunner.GivenAsync("пам\'ять заповнена значенями 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Дано ");
#line hidden
#line 5
  await testRunner.AndAsync(string.Format("ячейка 5 містить команду {0}", парам1), ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
#line 6
  await testRunner.AndAsync(string.Format("ячейка 18 містить команду {0}", парам2), ((string)(null)), ((global::Reqnroll.Table)(null)), "А також ");
#line hidden
#line 7
  await testRunner.AndAsync("ячейка 100 містить команду \'14 0005 0022 0002\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
#line 8
  await testRunner.AndAsync("регістр лічільник команд містить 100", ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
#line 9
  await testRunner.WhenAsync("виконати команді", ((string)(null)), ((global::Reqnroll.Table)(null)), "Якщо ");
#line hidden
#line 10
  await testRunner.ThenAsync(string.Format("ячейка 2 містить команду {0}", результат), ((string)(null)), ((global::Reqnroll.Table)(null)), "Тоді ");
#line hidden
#line 11
  await testRunner.AndAsync("лічільник команд містить 101", ((string)(null)), ((global::Reqnroll.Table)(null)), "А також ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Логічне множення")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Логічні операції")]
        [global::Xunit.TraitAttribute("Description", "Логічне множення")]
        [global::Xunit.InlineDataAttribute("\'37 7777 7777 7777\'", "\'00 0000 0000 0000\'", "\'00 0000 0000 0000\'", "3", new string[0])]
        [global::Xunit.InlineDataAttribute("\'00 0000 0000 0000\'", "\'00 0000 0000 0000\'", "\'00 0000 0000 0000\'", "4", new string[0])]
        [global::Xunit.InlineDataAttribute("\'00 0000 0000 0000\'", "\'12 5252 5252 5252\'", "\'00 0000 0000 0000\'", "5", new string[0])]
        [global::Xunit.InlineDataAttribute("\'37 7777 7777 7777\'", "\'37 7777 7777 7777\'", "\'37 7777 7777 7777\'", "6", new string[0])]
        public async global::System.Threading.Tasks.Task ЛогічнеМноження(string парам1, string парам2, string результат, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("парам1", парам1);
            argumentsOfScenario.Add("парам2", парам2);
            argumentsOfScenario.Add("результат", результат);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Логічне множення", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 19
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 20
  await testRunner.GivenAsync("пам\'ять заповнена значенями 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Дано ");
#line hidden
#line 21
  await testRunner.AndAsync(string.Format("ячейка 5 містить команду {0}", парам1), ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
#line 22
  await testRunner.AndAsync(string.Format("ячейка 18 містить команду {0}", парам2), ((string)(null)), ((global::Reqnroll.Table)(null)), "А також ");
#line hidden
#line 23
  await testRunner.AndAsync("ячейка 100 містить команду \'15 0005 0022 0002\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
#line 24
  await testRunner.AndAsync("регістр лічільник команд містить 100", ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
#line 25
  await testRunner.WhenAsync("виконати команді", ((string)(null)), ((global::Reqnroll.Table)(null)), "Якщо ");
#line hidden
#line 26
  await testRunner.ThenAsync(string.Format("ячейка 2 містить команду {0}", результат), ((string)(null)), ((global::Reqnroll.Table)(null)), "Тоді ");
#line hidden
#line 27
  await testRunner.AndAsync("лічільник команд містить 101", ((string)(null)), ((global::Reqnroll.Table)(null)), "А також ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Поразрядна однозначність")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Логічні операції")]
        [global::Xunit.TraitAttribute("Description", "Поразрядна однозначність")]
        [global::Xunit.InlineDataAttribute("\'25 2525 2525 2525\'", "\'52 5252 5252 5252\'", "\'00 0000 0000 0000\'", "7", new string[0])]
        [global::Xunit.InlineDataAttribute("\'52 5252 5252 5252\'", "\'25 2525 2525 2525\'", "\'00 0000 0000 0000\'", "8", new string[0])]
        [global::Xunit.InlineDataAttribute("\'52 5252 5252 5252\'", "\'52 5252 5252 5252\'", "\'37 7777 7777 7777\'", "9", new string[0])]
        [global::Xunit.InlineDataAttribute("\'25 2525 2525 2525\'", "\'25 2525 2525 2525\'", "\'37 7777 7777 7777\'", "10", new string[0])]
        public async global::System.Threading.Tasks.Task ПоразряднаОднозначність(string парам1, string парам2, string результат, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("парам1", парам1);
            argumentsOfScenario.Add("парам2", парам2);
            argumentsOfScenario.Add("результат", результат);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Поразрядна однозначність", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 36
 this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 37
  await testRunner.GivenAsync("пам\'ять заповнена значенями 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Дано ");
#line hidden
#line 38
  await testRunner.AndAsync(string.Format("ячейка 5 містить команду {0}", парам1), ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
#line 39
  await testRunner.AndAsync(string.Format("ячейка 18 містить команду {0}", парам2), ((string)(null)), ((global::Reqnroll.Table)(null)), "А також ");
#line hidden
#line 40
  await testRunner.AndAsync("ячейка 100 містить команду \'17 0005 0022 0002\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
#line 41
  await testRunner.AndAsync("регістр лічільник команд містить 100", ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
#line 42
  await testRunner.WhenAsync("виконати команді", ((string)(null)), ((global::Reqnroll.Table)(null)), "Якщо ");
#line hidden
#line 43
  await testRunner.ThenAsync(string.Format("ячейка 2 містить команду {0}", результат), ((string)(null)), ((global::Reqnroll.Table)(null)), "Тоді ");
#line hidden
#line 44
  await testRunner.AndAsync("лічільник команд містить 101", ((string)(null)), ((global::Reqnroll.Table)(null)), "А також ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ЛогічніОпераціїFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ЛогічніОпераціїFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
