// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Kyiv.Tests
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ЛогічніОпераціїFeature : object, Xunit.IClassFixture<ЛогічніОпераціїFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private static global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "ЛогічніОперації.feature"
#line hidden
        
        public ЛогічніОпераціїFeature(ЛогічніОпераціїFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(null, global::Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.GetWorkerId());
            global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("uk"), "", "Логічні операції", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
            await testRunner.OnFeatureStartAsync(featureInfo);
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            string testWorkerId = testRunner.TestWorkerId;
            await testRunner.OnFeatureEndAsync();
            testRunner = null;
            global::Reqnroll.xUnit.ReqnrollPlugin.XUnitParallelWorkerTracker.Instance.ReleaseWorker(testWorkerId);
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Логічне додавання")]
        [Xunit.TraitAttribute("FeatureTitle", "Логічні операції")]
        [Xunit.TraitAttribute("Description", "Логічне додавання")]
        [Xunit.InlineDataAttribute("\'00 0000 0000 0000\'", "\'37 7777 7777 7777\'", "\'37 7777 7777 7777\'", new string[0])]
        [Xunit.InlineDataAttribute("\'25 2525 2525 2525\'", "\'00 0000 0000 0000\'", "\'25 2525 2525 2525\'", new string[0])]
        [Xunit.InlineDataAttribute("\'37 7777 7777 7777\'", "\'37 7777 7777 7777\'", "\'37 7777 7777 7777\'", new string[0])]
        public async System.Threading.Tasks.Task ЛогічнеДодавання(string парам1, string парам2, string результат, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("парам1", парам1);
            argumentsOfScenario.Add("парам2", парам2);
            argumentsOfScenario.Add("результат", результат);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Логічне додавання", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 3
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
  await testRunner.GivenAsync("пам\'ять заповнена значенями 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Дано ");
#line hidden
#line 5
  await testRunner.AndAsync(string.Format("ячейка 5 містить команду {0}", парам1), ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
#line 6
  await testRunner.AndAsync(string.Format("ячейка 18 містить команду {0}", парам2), ((string)(null)), ((global::Reqnroll.Table)(null)), "А також ");
#line hidden
#line 7
  await testRunner.AndAsync("ячейка 100 містить команду \'14 0005 0022 0002\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
#line 8
  await testRunner.AndAsync("регістр лічільник команд містить 100", ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
#line 9
  await testRunner.WhenAsync("виконати команді", ((string)(null)), ((global::Reqnroll.Table)(null)), "Якщо ");
#line hidden
#line 10
  await testRunner.ThenAsync(string.Format("ячейка 2 містить команду {0}", результат), ((string)(null)), ((global::Reqnroll.Table)(null)), "Тоді ");
#line hidden
#line 11
  await testRunner.AndAsync("лічільник команд містить 101", ((string)(null)), ((global::Reqnroll.Table)(null)), "А також ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Логічне множення")]
        [Xunit.TraitAttribute("FeatureTitle", "Логічні операції")]
        [Xunit.TraitAttribute("Description", "Логічне множення")]
        [Xunit.InlineDataAttribute("\'37 7777 7777 7777\'", "\'00 0000 0000 0000\'", "\'00 0000 0000 0000\'", new string[0])]
        [Xunit.InlineDataAttribute("\'00 0000 0000 0000\'", "\'00 0000 0000 0000\'", "\'00 0000 0000 0000\'", new string[0])]
        [Xunit.InlineDataAttribute("\'00 0000 0000 0000\'", "\'12 5252 5252 5252\'", "\'00 0000 0000 0000\'", new string[0])]
        [Xunit.InlineDataAttribute("\'37 7777 7777 7777\'", "\'37 7777 7777 7777\'", "\'37 7777 7777 7777\'", new string[0])]
        public async System.Threading.Tasks.Task ЛогічнеМноження(string парам1, string парам2, string результат, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("парам1", парам1);
            argumentsOfScenario.Add("парам2", парам2);
            argumentsOfScenario.Add("результат", результат);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Логічне множення", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 19
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 20
  await testRunner.GivenAsync("пам\'ять заповнена значенями 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Дано ");
#line hidden
#line 21
  await testRunner.AndAsync(string.Format("ячейка 5 містить команду {0}", парам1), ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
#line 22
  await testRunner.AndAsync(string.Format("ячейка 18 містить команду {0}", парам2), ((string)(null)), ((global::Reqnroll.Table)(null)), "А також ");
#line hidden
#line 23
  await testRunner.AndAsync("ячейка 100 містить команду \'15 0005 0022 0002\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
#line 24
  await testRunner.AndAsync("регістр лічільник команд містить 100", ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
#line 25
  await testRunner.WhenAsync("виконати команді", ((string)(null)), ((global::Reqnroll.Table)(null)), "Якщо ");
#line hidden
#line 26
  await testRunner.ThenAsync(string.Format("ячейка 2 містить команду {0}", результат), ((string)(null)), ((global::Reqnroll.Table)(null)), "Тоді ");
#line hidden
#line 27
  await testRunner.AndAsync("лічільник команд містить 101", ((string)(null)), ((global::Reqnroll.Table)(null)), "А також ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Поразрядна однозначність")]
        [Xunit.TraitAttribute("FeatureTitle", "Логічні операції")]
        [Xunit.TraitAttribute("Description", "Поразрядна однозначність")]
        [Xunit.InlineDataAttribute("\'25 2525 2525 2525\'", "\'52 5252 5252 5252\'", "\'00 0000 0000 0000\'", new string[0])]
        [Xunit.InlineDataAttribute("\'52 5252 5252 5252\'", "\'25 2525 2525 2525\'", "\'00 0000 0000 0000\'", new string[0])]
        [Xunit.InlineDataAttribute("\'52 5252 5252 5252\'", "\'52 5252 5252 5252\'", "\'37 7777 7777 7777\'", new string[0])]
        [Xunit.InlineDataAttribute("\'25 2525 2525 2525\'", "\'25 2525 2525 2525\'", "\'37 7777 7777 7777\'", new string[0])]
        public async System.Threading.Tasks.Task ПоразряднаОднозначність(string парам1, string парам2, string результат, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("парам1", парам1);
            argumentsOfScenario.Add("парам2", парам2);
            argumentsOfScenario.Add("результат", результат);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Поразрядна однозначність", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 36
 this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 37
  await testRunner.GivenAsync("пам\'ять заповнена значенями 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Дано ");
#line hidden
#line 38
  await testRunner.AndAsync(string.Format("ячейка 5 містить команду {0}", парам1), ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
#line 39
  await testRunner.AndAsync(string.Format("ячейка 18 містить команду {0}", парам2), ((string)(null)), ((global::Reqnroll.Table)(null)), "А також ");
#line hidden
#line 40
  await testRunner.AndAsync("ячейка 100 містить команду \'17 0005 0022 0002\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
#line 41
  await testRunner.AndAsync("регістр лічільник команд містить 100", ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
#line 42
  await testRunner.WhenAsync("виконати команді", ((string)(null)), ((global::Reqnroll.Table)(null)), "Якщо ");
#line hidden
#line 43
  await testRunner.ThenAsync(string.Format("ячейка 2 містить команду {0}", результат), ((string)(null)), ((global::Reqnroll.Table)(null)), "Тоді ");
#line hidden
#line 44
  await testRunner.AndAsync("лічільник команд містить 101", ((string)(null)), ((global::Reqnroll.Table)(null)), "А також ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ЛогічніОпераціїFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ЛогічніОпераціїFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
