// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Kyiv.Tests
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ПорівнянняFeature : object, global::Xunit.IClassFixture<ПорівнянняFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("uk"), "", "Порівняння", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Переходи.feature"
#line hidden
        
        public ПорівнянняFeature(ПорівнянняFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Переходи.feature.ndjson", 12);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Порівняння без знака")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Порівняння")]
        [global::Xunit.TraitAttribute("Description", "Порівняння без знака")]
        [global::Xunit.InlineDataAttribute("\'00 0000 0000 1100\'", "\'00 0000 0000 0300\'", "101", "0", new string[0])]
        [global::Xunit.InlineDataAttribute("\'00 0000 0000 0100\'", "\'00 0000 0000 0300\'", "2", "1", new string[0])]
        [global::Xunit.InlineDataAttribute("\'00 0000 0000 0100\'", "\'00 0000 0000 0100\'", "2", "2", new string[0])]
        [global::Xunit.InlineDataAttribute("\'00 0000 0000 0100\'", "\'70 0000 0000 0100\'", "2", "3", new string[0])]
        public async global::System.Threading.Tasks.Task ПорівнянняБезЗнака(string значення1, string значення2, string лічільник, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("значення1", значення1);
            argumentsOfScenario.Add("значення2", значення2);
            argumentsOfScenario.Add("лічільник", лічільник);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Порівняння без знака", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 3
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
 await testRunner.GivenAsync("пам\'ять заповнена значенями 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Дано ");
#line hidden
#line 5
 await testRunner.AndAsync(string.Format("ячейка 5 містить команду {0}", значення1), ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
#line 6
 await testRunner.AndAsync(string.Format("ячейка 18 містить команду {0}", значення2), ((string)(null)), ((global::Reqnroll.Table)(null)), "А також ");
#line hidden
#line 7
 await testRunner.AndAsync("ячейка 100 містить команду \'05 0005 0022 0002\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
#line 8
 await testRunner.AndAsync("регістр лічільник команд містить 100", ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
#line 9
 await testRunner.WhenAsync("виконати команді", ((string)(null)), ((global::Reqnroll.Table)(null)), "Якщо ");
#line hidden
#line 10
 await testRunner.ThenAsync(string.Format("лічільник команд містить {0}", лічільник), ((string)(null)), ((global::Reqnroll.Table)(null)), "Тоді ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Перехід по регістру повернення")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Порівняння")]
        [global::Xunit.TraitAttribute("Description", "Перехід по регістру повернення")]
        public async global::System.Threading.Tasks.Task ПерехідПоРегіструПовернення()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Перехід по регістру повернення", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 19
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 20
 await testRunner.GivenAsync("пам\'ять заповнена значенями 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Дано ");
#line hidden
#line 21
 await testRunner.AndAsync("регістр повернення містить 18", ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
#line 22
 await testRunner.AndAsync("ячейка 18 містить команду \'05 0005 0022 0002\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "А також ");
#line hidden
#line 23
 await testRunner.AndAsync("ячейка 100 містить команду \'32 0000 0000 0000\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
#line 24
 await testRunner.AndAsync("регістр лічільник команд містить 100", ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
#line 25
 await testRunner.WhenAsync("виконати команді", ((string)(null)), ((global::Reqnroll.Table)(null)), "Якщо ");
#line hidden
#line 26
 await testRunner.ThenAsync("лічільник команд містить 18", ((string)(null)), ((global::Reqnroll.Table)(null)), "Тоді ");
#line hidden
#line 27
 await testRunner.AndAsync("регістр повернення містить 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Початок групової команди")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Порівняння")]
        [global::Xunit.TraitAttribute("Description", "Початок групової команди")]
        [global::Xunit.InlineDataAttribute("\'26 0005 0022 0002\'", "18", "101", "5", new string[0])]
        [global::Xunit.InlineDataAttribute("\'26 0005 0005 0002\'", "5", "2", "6", new string[0])]
        public async global::System.Threading.Tasks.Task ПочатокГруповоїКоманди(string значення1, string регістрМодіфікаціїАдреси, string лічільник, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("значення1", значення1);
            argumentsOfScenario.Add("регістр модіфікації адреси", регістрМодіфікаціїАдреси);
            argumentsOfScenario.Add("лічільник", лічільник);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Початок групової команди", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 29
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 30
 await testRunner.GivenAsync("пам\'ять заповнена значенями 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Дано ");
#line hidden
#line 31
 await testRunner.AndAsync("ячейка 2 містить команду \'32 0015 0012 0002\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "А також ");
#line hidden
#line 32
 await testRunner.AndAsync(string.Format("ячейка 100 містить команду {0}", значення1), ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
#line 33
 await testRunner.AndAsync("регістр лічільник команд містить 100", ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
#line 34
 await testRunner.WhenAsync("виконати команді", ((string)(null)), ((global::Reqnroll.Table)(null)), "Якщо ");
#line hidden
#line 35
 await testRunner.ThenAsync(string.Format("лічільник команд містить {0}", лічільник), ((string)(null)), ((global::Reqnroll.Table)(null)), "Тоді ");
#line hidden
#line 36
 await testRunner.AndAsync("регістр циклу містить 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
#line 37
 await testRunner.AndAsync(string.Format("регістр модифікації адрес містить {0}", регістрМодіфікаціїАдреси), ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Кінець групової команди")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Порівняння")]
        [global::Xunit.TraitAttribute("Description", "Кінець групової команди")]
        [global::Xunit.InlineDataAttribute("\'27 0001 0022 0002\'", "6", "18", "7", new string[0])]
        [global::Xunit.InlineDataAttribute("\'27 0005 0022 0002\'", "10", "2", "8", new string[0])]
        [global::Xunit.InlineDataAttribute("\'27 4001 0022 0002\'", "6", "18", "9", new string[0])]
        public async global::System.Threading.Tasks.Task КінецьГруповоїКоманди(string значення1, string регістрМодіфікаціїАдреси, string лічільник, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("значення1", значення1);
            argumentsOfScenario.Add("регістр модіфікації адреси", регістрМодіфікаціїАдреси);
            argumentsOfScenario.Add("лічільник", лічільник);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Кінець групової команди", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 44
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 45
 await testRunner.GivenAsync("пам\'ять заповнена значенями 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Дано ");
#line hidden
#line 46
 await testRunner.AndAsync("регістр циклу містить 10", ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
#line 47
 await testRunner.AndAsync("регістр модифікації адрес містить 5", ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
#line 48
 await testRunner.AndAsync(string.Format("ячейка 100 містить команду {0}", значення1), ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
#line 49
 await testRunner.AndAsync("регістр лічільник команд містить 100", ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
#line 50
 await testRunner.WhenAsync("виконати команді", ((string)(null)), ((global::Reqnroll.Table)(null)), "Якщо ");
#line hidden
#line 51
 await testRunner.ThenAsync(string.Format("лічільник команд містить {0}", лічільник), ((string)(null)), ((global::Reqnroll.Table)(null)), "Тоді ");
#line hidden
#line 52
 await testRunner.AndAsync("регістр циклу містить 10", ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
#line 53
 await testRunner.AndAsync(string.Format("регістр модифікації адрес містить {0}", регістрМодіфікаціїАдреси), ((string)(null)), ((global::Reqnroll.Table)(null)), "І ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await ПорівнянняFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await ПорівнянняFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
