//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kyiv.Макет {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Ресурси {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ресурси() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kyiv.Макет.Ресурси", typeof(Ресурси).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your locale:.
        /// </summary>
        internal static string ВиберітьКультуру {
            get {
                return ResourceManager.GetString("ВиберітьКультуру", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About project.
        /// </summary>
        internal static string ПроПроект {
            get {
                return ResourceManager.GetString("ПроПроект", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string СторінкаГоловна {
            get {
                return ResourceManager.GetString("СторінкаГоловна", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompiler.
        /// </summary>
        internal static string СторінкаДекомпілятор {
            get {
                return ResourceManager.GetString("СторінкаДекомпілятор", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disassembler.
        /// </summary>
        internal static string СторінкаДізасемблер {
            get {
                return ResourceManager.GetString("СторінкаДізасемблер", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        internal static string СторінкаКоманди {
            get {
                return ResourceManager.GetString("СторінкаКоманди", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constants.
        /// </summary>
        internal static string СторінкаКонстанти {
            get {
                return ResourceManager.GetString("СторінкаКонстанти", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inaccuracies.
        /// </summary>
        internal static string СторінкаНеточності {
            get {
                return ResourceManager.GetString("СторінкаНеточності", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM.
        /// </summary>
        internal static string СторінкаОЗП {
            get {
                return ResourceManager.GetString("СторінкаОЗП", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROM.
        /// </summary>
        internal static string СторінкаПЗП {
            get {
                return ResourceManager.GetString("СторінкаПЗП", resourceCulture);
            }
        }
    }
}
